### PR TITLE
Turned TokenDisplay component back into tsx

### LINKED ISSUE #15: Convert `TokenDisplay.jsx` back into tsx

### PR DESCRIPTION
**Pull request by alecrem**
Closes #15

### CODE REVIEW

**Comment by alecrem** [comment]
@yuwa2020 I had some time, so I turned it back into a tsx.

Some changes are just Prettier formatting as per the project's settings. Sorry about those.

**Comment by yuwa2020** [comment]
@alecrem 
Thanks!!

**Review by yuwa2020 — APPROVED** [review]
I reviewed the code.
No problem.

**Comment by alecrem** [comment]
Thank yo for the review, @yuwa2020! Merging now.

**Pull request merged**
