### PR TITLE
Finding the token ID for owned tokens

### LINKED ISSUE #8: The site needs to fetch the tokens' metadata

### PR DESCRIPTION
**Pull request by alecrem**
Closes #8

### CODE REVIEW

**Comment by alecrem** [comment]
@yuwa2020 Could I get a review from you?

This could be enough:

- Connect your wallet to the latest deployment
- Check that the green hiragana labels link to each token's JSON metadata

Any improvements or suggestions are welcome too, of course! But it should be good to merge this soon if it's not too bad.

**Comment by yuwa2020** [comment]
It works.
- Connect your wallet to the latest deployment
Screen Shot 2022-09-10 at 7 08 11 PM
a9289.png">

**Review by yuwa2020 — COMMENTED** [review]
It works.
There is no problem.
- Connect your wallet to the latest deployment
Screen Shot 2022-09-10 at 7 08 11 PM


- Check that the green hiragana labels link to each token's JSON metadata
Screen Shot 2022-09-10 at 7 08 48 PM

**Comment by alecrem** [comment]
@yuwa2020 Thank you for checking!

Could you review and approve the PR, if you think it's OK?

Edit: Sorry! I see that you did review, with just a comment. Could you approve the PR if you think it's OK?

Sometimes a PR needs to be approved before merging, although we don't have that enabled on this repository. I guess it's better to approve if you saw no problem. (I don't think we need to thoroughly review all the code at this point, but please let me know if you find something that you don't like 🙇)

**Pull request merged**
